//go:build ignore
// +build ignore

package main

import (
	"bufio"
	"fmt"
	"io"
	"net/http"
	"os"
	"sort"
	"strings"
)

// OUI entry from IEEE registry
type OUIEntry struct {
	OUI        string
	Manufacturer string
}

func main() {
	// Download IEEE OUI registry
	fmt.Fprintln(os.Stderr, "Downloading IEEE OUI registry...")
	resp, err := http.Get("https://standards-oui.ieee.org/oui/oui.txt")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to download OUI registry: %v\n", err)
		os.Exit(1)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		fmt.Fprintf(os.Stderr, "HTTP error: %s\n", resp.Status)
		os.Exit(1)
	}

	// Parse the registry
	entries := parseOUIRegistry(resp.Body)

	fmt.Fprintf(os.Stderr, "Parsed %d OUI entries\n", len(entries))

	// Generate Go source file
	fmt.Println("// Code generated by go generate. DO NOT EDIT.")
	fmt.Println()
	fmt.Println("package oui")
	fmt.Println()
	fmt.Println("// ouiMap maps 24-bit OUIs to manufacturer names")
	fmt.Println("var ouiMap = map[uint32]string{")

	for _, e := range entries {
		// Convert AA-BB-CC format to integer key
		parts := strings.Split(e.OUI, "-")
		if len(parts) != 3 {
			continue
		}
		key := (hexToInt(parts[0]) << 16) | (hexToInt(parts[1]) << 8) | hexToInt(parts[2])
		fmt.Printf("0x%06X: %q,\n", key, e.Manufacturer)
	}

	fmt.Println("}")
}

func parseOUIRegistry(r io.Reader) []OUIEntry {
	var entries []OUIEntry
	scanner := bufio.NewScanner(r)

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())

		// Skip empty lines and comments
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		// Parse OUI line: "AA-BB-CC   (hex)	Manufacturer Name"
		parts := strings.SplitN(line, "\t", 3)
		if len(parts) < 3 {
			continue
		}

		oui := strings.TrimSpace(parts[0])
		if !strings.Contains(parts[1], "(hex)") {
			continue
		}

		manufacturer := strings.TrimSpace(parts[2])
		if manufacturer == "" {
			continue
		}

		entries = append(entries, OUIEntry{
			OUI:        oui,
			Manufacturer: manufacturer,
		})
	}

	// Sort by OUI for deterministic output
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].OUI < entries[j].OUI
	})

	return entries
}

func hexToInt(s string) uint32 {
	var val uint32
	fmt.Sscanf(s, "%x", &val)
	return val
}
